# Generated by Django 4.2 on 2023-05-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("converter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Курс валют"},
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="rate",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="Курс валюты (USD)"
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(max_length=10, verbose_name="Краткое обозначение"),
        ),
    ]
