# Generated by Django 4.2 on 2023-05-03 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("converter", "0002_alter_currency_options_alter_currency_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={
                "verbose_name": "Курс валюты",
                "verbose_name_plural": "Курсы валют",
            },
        ),
    ]
